"""Add titanium fields

Revision ID: e1a8635a344d
Revises: 0aa416a8efdf
Create Date: 2026-02-16 21:04:13.106725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a8635a344d'
down_revision = '0aa416a8efdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bloque', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aditamento_holder', sa.String(length=50), nullable=True))

    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aditamento_holder', sa.String(length=50), nullable=True))
        batch_op.alter_column('codigo_barra',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orden', schema=None) as batch_op:
        batch_op.alter_column('codigo_barra',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.drop_column('aditamento_holder')

    with op.batch_alter_table('bloque', schema=None) as batch_op:
        batch_op.drop_column('aditamento_holder')

    # ### end Alembic commands ###
